package com.vlesscardvpn.core

/**
 * Built-in ad-blocking DNS rules for sing-box.
 * Blocks ads, trackers, malware, and telemetry domains at DNS level.
 * Curated subset of OISD/Hagezi blocklists optimized for mobile.
 */
object AdBlockDns {
    // High-impact ad/tracker domains — compact list for mobile performance
    val adBlockRules: List<String> = listOf(
        // Google Ads & Analytics
        "doubleclick.net",
        "googlesyndication.com",
        "googleadservices.com",
        "googletagmanager.com",
        "googletagservices.com",
        "google-analytics.com",
        "googleadservices.com",
        "googleads.g.doubleclick.net",
        "adservice.google.com",
        "pagead2.googlesyndication.com",
        "adservice.google.com",
        // Facebook / Meta
        "facebook.com/tr",
        "fbcdn.net",
        "atdmt.com",
        "facebook.net",
        // Amazon Ads
        "amazon-adsystem.com",
        "aax-us-east.amazon-adsystem.com",
        // AppLovin / Unity Ads
        "applovin.com",
        "unity3d.com",
        // Yandex Ads
        "yandexadexchange.net",
        "yandex.ru/clck",
        "yandex.ru/jkclick",
        "yads.yandex.ru",
        "mc.yandex.ru",
        "an.yandex.ru",
        "bs.yandex.ru",
        "adsdk.yandex.ru",
        // VK / MyTarget
        "my.com",
        "mycdn.me",
        "target.my.com",
        "ad.mail.ru",
        "top-fwz1.mail.ru",
        "rs.mail.ru",
        // Analytics & Telemetry
        "adjust.com",
        "appsflyer.com",
        "branch.io",
        "firebase-settings.crashlytics.com",
        "firebaselogging.googleapis.com",
        "app-measurement.com",
        "mixpanel.com",
        "amplitude.com",
        "segment.com",
        "walkme.com",
        "hotjar.com",
        "mouseflow.com",
        "fullstory.com",
        "newrelic.com",
        "datadoghq.com",
        "sentry.io",
        "bugsnag.com",
        "instabug.com",
        "clevertap.com",
        "moengage.com",
        "leanplum.com",
        "onesignal.com",
        "braze.com",
        "iterable.com",
        "webengage.com",
        "uxcam.com",
        "quantummetric.com",
        "contentsquare.com",
        "heap.io",
        "pendo.io",
        "productboard.com",
        "optimizely.com",
        // Ad Networks
        "adcolony.com",
        "adincube.com",
        "admob.com",
        "adzerk.net",
        "chartboost.com",
        "criteo.com",
        "criteo.net",
        "fyber.com",
        "inmobi.com",
        "ironsrc.com",
        "ironsrcads.com",
        "mintegral.com",
        "mopub.com",
        "ogury.com",
        "openx.net",
        "pubmatic.com",
        "rubiconproject.com",
        "smaato.com",
        "smartadserver.com",
        "startapp.com",
        "supersonicads.com",
        "taboola.com",
        "tapjoy.com",
        "tremorhub.com",
        "vungle.com",
        "yieldmo.com",
        "moloco.com",
        "bidmachine.io",
        "vrtcal.com",
        "appier.com",
        "aarki.com",
        "adperium.com",
        "advertising.com",
        "adzerk.com",
        "airpush.com",
        "alkimi.com",
        "algorix.co",
        "appier.com",
        "applvn.com",
        "appodeal.com",
        "apsalar.com",
        "rekmob.com",
        "revmob.com",
        "scorecardresearch.com",
        "sharethrough.com",
        "smaato.net",
        "spotxchange.com",
        "tremorhub.com",
        "triplelift.com",
        "verve.com",
        "vrtz.com",
        // Chinese Ad Networks
        "adkwai.com",
        "bytedance.com",
        "byted.org",
        "byteimg.com",
        "byteoversea.com",
        "pangle.io",
        "pangleglobal.com",
        "snssdk.com",
        "toutiao.com",
        "tiktokv.com",
        // Malware / Phishing TLDs
        "xxx",
        "xyz",
        "top",
        "work",
        "click",
        "link",
        "gdn",
        "download",
        "party",
        "review",
        "country",
        "stream",
        "loan",
        "win",
        "racing",
        "accountant",
        "science",
        "date",
        "faith",
        // Trackers
        "scorecardresearch.com",
        "outbrain.com",
        "bluekai.com",
        "exelator.com",
        "demdex.net",
        "krxd.net",
        "adsrvr.org",
        "adnxs.com",
        "1rx.io",
        "adtdp.com",
        "3lift.com",
        "bidswitch.net",
        "casalemedia.com",
        "contextweb.com",
        "lijit.com",
        "media.net",
        "moatads.com",
        "nexac.com",
        "openx.net",
        "rhythmone.com",
        "rubiconproject.com",
        "sharethrough.com",
        "sovrn.com",
        "spotx.tv",
        "teads.tv",
        "tidaltv.com",
        "triplelift.com",
        "trustx.org",
        "undertone.com",
        "unruly.com",
        "vidible.tv",
        "widespace.com",
        "yume.com",
        "zemanta.com",
        // Russian trackers
        "top100.ru",
        "rambler.ru",
        "spylog.com",
        "liveinternet.ru",
        "yadro.ru",
        "tns-counter.ru",
        "count.yandex.ru",
        "informer.yandex.ru",
        "mediascope.net",
        "adriver.ru",
        "adfox.ru",
        "beboo.ru",
        "begun.ru",
        "creatium.ru",
        // Xiaomi trackers
        "api.sec.miui.com",
        "tracking.miui.com",
        "sentry.miui.com",
        "metok.miui.com",
        "data.mistat.xiaomi.com",
        "globalapi.mi.com",
        "tracking.intl.miui.com",
        "ccc.sys.miui.com",
        "flash.android.intl.xiaomi.com",
        "us-o2o.intl.miui.com",
        "adv.sec.intl.miui.com",
        "api.branch.io",
        "sdkconfig.ad.intl.xiaomi.com",
        "new.api.ad.xiaomi.com",
        "tracker.ad.intl.xiaomi.com",
        // Samsung trackers
        "samsungclick.com",
        "samsungacr.com",
        "samsungads.com",
        "samsung-com.112.2o7.net",
        "ad.samsungadhub.com",
        "config.samsungads.com",
        "gmp.samsungapps.com",
        // Huawei trackers
        "metrics.hicloud.com",
        "metrics2.hicloud.com",
        "logservice.hicloud.com",
        "logservice1.hicloud.com",
        "logbak.hicloud.com",
        "hwad.hicloud.com",
        "hwworship.hicloud.com",
        "adx.hicloud.com",
        "push-api.cloud.huawei.com",
        "api-appstore.hicloud.com",
        "hivendor.hicloud.com",
        "connectivitycheck.platform.hicloud.com",
        // Oppo/Vivo
        "api.adx.oppomobile.com",
        "adsfs.oppomobile.com",
        "adx.oppomobile.com",
        "bdapi.ads.oppomobile.com",
        "data.ads.oppomobile.com",
        "g1.ads.oppomobile.com",
        "httpdns.push.oppomobile.com",
        "stg.data.ads.oppomobile.com",
        "adx.vivo.com.cn",
        "adsdk.vivo.com.cn",
        "adsstatic.vivo.com.cn",
        "adreq.vivo.com.cn",
        "stsdk.vivo.com.cn",
        "vcds.vivo.com.cn",
        // OnePlus
        "adsfs.oneplus.com",
        "open.oneplus.net",
        "logservice.oneplus.com",
        "tracker.oneplus.com",
        // Realme
        "adx.realme.com",
        "adsfs.realme.com",
        "bdapi.ads.realme.com",
        "api.log.realme.com",
        // Moto/Lenovo
        "idm.iot. lenovo.com",
        "ad.api.lenovo.com",
        "api.ads.lenovo.com",
        // Telegram
        "promo.telegram.org",
        // Misc ad CDNs
        "cdn.ampproject.org/v/s",
        "pagead2.googlesyndication.com",
        "tpc.googlesyndication.com",
        "fundingchoicesmessages.google.com",
        "ad.doubleclick.net",
        "static.doubleclick.net",
        "m.doubleclick.net",
        "mediavisor.doubleclick.net",
        "ads30.adcolony.com",
        "adsdk.appsflyer.com",
        "launches.appsflyer.com",
        "t.appsflyer.com",
        "inapps.appsflyer.com",
        "cdn.appsflyer.com",
        "track.appsflyer.com"
    )
}