package com.vlesscardvpn.domain

data class VlessConfig(
    val id: String = java.util.UUID.randomUUID().toString(),
    val name: String,
    val address: String,
    val port: Int,
    val uuid: String,
    val protocolType: String = "vless", // vless, vmess, trojan, ss
    val flow: String = "xtls-rprx-vision",
    val security: String = "reality",
    val sni: String = "yandex.ru",
    val fingerprint: String = "chrome",
    val publicKey: String = "",
    val shortId: String = "",
    val remark: String = "",
    val isActive: Boolean = false,
    val pingMs: Int = -1,
    val isFree: Boolean = false,
    val country: String = "Unknown",
    val addedAt: Long = System.currentTimeMillis(),
    val lastCheck: Long = 0L,
    val healthState: String = "UNKNOWN", // UNKNOWN, HEALTHY, DEGRADED, DEAD
    val failureCount: Int = 0,
    val source: String = "manual",
    val isFavorite: Boolean = false,
    val tcpLatencyMs: Int = -1,
    val tlsLatencyMs: Int = -1,
    val httpLatencyMs: Int = -1
)

data class AppSettings(
    val isDarkTheme: Boolean = true,
    val autoSelect: Boolean = false,
    val autoSelectBestPing: Boolean = true,
    val healthCheckInterval: Int = 30, // seconds
    val failoverEnabled: Boolean = true,
    val lastWorkingConfigId: String = "",
    val enableRuDirect: Boolean = true,
    val blockQuicYouTube: Boolean = true,
    val customSniOverride: String = "auto",
    val customDnsProvider: String = "Cloudflare (1.1.1.1)",
    val mtuSize: Int = 1400,
    val autoReconnectOnNetworkChange: Boolean = true,
    val autoTestAfterImport: Boolean = true,
    val includeFreeNodesInMainList: Boolean = true,
    val showOnlyWorkingNodes: Boolean = false,
    val deduplicateNodes: Boolean = true,
    val maxFreeNodesToAdd: Int = 100,
    val autopilotConsentGiven: Boolean = false,
    val autopilotAllowedOnlyFavorites: Boolean = false,
    val autopilotAggressiveAdapting: Boolean = false,
    val githubIssuesRepo: String = "github.com/vless-card-vpn/vless-card-vpn",
    val githubApiToken: String = "",
    val autoSendCrashReportsConsent: Boolean = false,
    val autoFetchSources: List<String> = listOf(
        "https://raw.githubusercontent.com/0xRadikal/Free-v2ray-Configs/main/verified/configs.txt",
        "https://raw.githubusercontent.com/0xRadikal/Free-v2ray-Configs/main/all/vless.txt",
        "https://raw.githubusercontent.com/Danialsamadi/v2go/main/Sub1.txt",
        "https://raw.githubusercontent.com/Danialsamadi/v2go/main/Sub2.txt",
        "https://raw.githubusercontent.com/Danialsamadi/v2go/main/AllConfigsSub.txt",
        "https://raw.githubusercontent.com/Danialsamadi/v2go/main/Splitted-By-Protocol/vless.txt",
        "https://raw.githubusercontent.com/mehdirzfx/v2ray-sub/main/vless",
        "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/Vless-Reality-White-Lists-Rus-Mobile.txt",
        "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/Vless-Reality-White-Lists-Rus-Mobile-2.txt",
        "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/BLACK_VLESS_RUS.txt",
        "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/BLACK_VLESS_RUS_mobile.txt",
        "https://raw.githubusercontent.com/kort0881/vpn-vless-configs-russia/main/githubmirror/clean/vless.txt",
        "https://raw.githubusercontent.com/kort0881/vpn-vless-configs-russia/main/githubmirror/ru-sni/vless_ru.txt",
        "https://raw.githubusercontent.com/kort0881/vpn-vless-configs-russia/main/configs/vless_reality.txt",
        "https://raw.githubusercontent.com/ByeWhiteLists/ByeWhiteLists2/refs/heads/main/ByeWhiteLists2.txt",
        "https://raw.githubusercontent.com/barry-far/V2ray-Config/main/Splitted-By-Protocol/vless.txt",
        "https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vless.txt",
        "https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vless",
        "https://raw.githubusercontent.com/Mosifree/-FREE2CONFIG/refs/heads/main/Reality",
        "https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt",
        "https://raw.githubusercontent.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/26.txt"
    )
)
